import type { Metadata } from 'next';
import './globals.css';
import Wrapper from './wrapper';

export const metadata: Metadata = {
  title: 'Perlin Spotify Flow',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={'box-border overflow-hidden'}>
        <Wrapper>{children}</Wrapper>
        {/*       
        <P5jsContainer /> */}
      </body>
    </html>
  );
}
