import type { Metadata } from 'next';
import './globals.css';
import { P5jsContainer } from '@/components/p5jsContainer';

export const metadata: Metadata = {
  title: 'Perlin Spotify Flow',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={'box-border overflow-hidden'}>
        {children}
        <P5jsContainer />
      </body>
    </html>
  );
}
